### ISSUE TITLE
Length of vector a (512) must be equal to the length of vector b (1536)

### ISSUE THREAD

**Issue by 983183947** [tencentmusic/supersonic#1179]
我在使用过程中发现向量有报错。但是结果又能出来，我需要配置什么吗
```
java.lang.IllegalArgumentException: Length of vector a (512) must be equal to the length of vector b (1536)
	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.store.embedding.CosineSimilarity.between(CosineSimilarity.java:48)
	at dev.langchain4j.store.embedding.InMemoryS2EmbeddingStore$InMemoryEmbeddingStore.findRelevant(InMemoryS2EmbeddingStore.java:290)
	at dev.langchain4j.store.embedding.EmbeddingStore.findRelevant(EmbeddingStore.java:131)
	at dev.langchain4j.store.embedding.InMemoryS2EmbeddingStore.retrieveQuery(InMemoryS2EmbeddingStore.java:137)
	at com.tencent.supersonic.chat.server.util.SimilarQueryManager.recallSimilarQuery(SimilarQueryManager.java:84)
	at com.tencent.supersonic.chat.server.processor.parse.QueryRecommendProcessor.getSimilarQueries(QueryRecommendProcessor.java:49)
	at com.tencent.supersonic.chat.server.processor.parse.QueryRecommendProcessor.doProcess(QueryRecommendProcessor.java:39)
	at com.tencent.supersonic.chat.server.processor.parse.QueryRecommendProcessor.lambda$process$0(QueryRecommendProcessor.java:33)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

```

**Comment by 983183947** [comment]
清理下缓存就行了
rm  /tmp/*collection
