### ISSUE TITLE
希望能支持达梦数据库

### ISSUE THREAD

**Issue by Yanzzang** [tencentmusic/supersonic#1191]
**将达梦数据库jdbc驱动加入到lib目录下，在数据库管理功能下无法连接成功。**

不知道有什么解决方案，或者希望下一版进行支持～～

**Comment by jerryjzhang** [comment]
你好，可以贴一下报错的日志吗

**Comment by Yanzzang** [comment]
在数据库管理功能下，用postgresql或mysql，error.chat.log报错日志如下（其他日志也都有相同的信息）：
(1)
error [supersonic_xxxxx] c.t.s.h.c.utils.JdbcDataSourceUtils 116 - e
java.sql.SQLException: No suitable driver
    at java.sql.DriverManager.getDriver(DriverManager.java:315)
    at com.tencent.supersonic.headless.core.utils.JdbcDataSourceUtils.getDriverClassName(JdbcDataSourceUtils.java:114)
    xxxxx
(2)
error [supersonic_xxxxx] c.t.s.advice.RestExceptionHandler 25 - default global exception
java.lang.RuntimeException: Not support data type: jdbcUrl=jdbc:dm://xx.xx.xx.xx:xx
    at com.tencent.supersonic.headless.core.utils.JdbcDataSourceUtils.getDriverClassName(JdbcDataSourceUtils.java:128)
    xxxxx

**Comment by jerryjzhang** [comment]
这个应该是在lib目录下没有达梦的jdbc驱动文件，可以在下面的链接下载
https://eco.dameng.com/download/

**Comment by jerryjzhang** [comment]
https://eco.dameng.com/download/

**Comment by jerryjzhang** [comment]
已经规划在0.9.6版本取消对数据库类型的限制，理论上只要将数据库的jdbc驱动文件放入supersonic的lib目录，即可正常对接，可以参考 #1490

**Comment by lxwcodemonkey** [comment]
![image](https://github.com/user-attachments/assets/304f1dbd-c43f-4948-b37a-e19996d33ce9)
当SQL中带有`符号时，可能会导致异常，需要进行兼容

**Comment by Echo0o0o0o0** [comment]
<img width="1722" height="357" alt="Image" src="https://github.com/user-attachments/assets/585e3f47-9c1f-4338-bbea-3d52e478f2b0" />生成sql的语法与达梦的语法不兼容
