### ISSUE TITLE
Mysql数据源，同一实例下，连库不支持[Bug] 

### ISSUE THREAD

**Issue by JackLiang** [tencentmusic/supersonic#1418]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.6

### What's Wrong?

2024-07-17 19:46:31,876 [http-nio-9080-exec-8] INFO  [supersonic_2fdcca85158b41a2b8f28de47b5b69ad] c.t.s.h.c.t.c.sql.render.JoinRender 110 - tableView (SELECT `lot_num`, `lot_att01` AS `lot_att01`, `lot_att04` AS `lot_att04` FROM (WITH `dict` AS (SELECT `dict_code`, `code`, `name` FROM `dc_anlianyun_656859700b3d_ver`.`data_dictionary_detail`) SELECT `lot`.`id`, `lot`.`lot_num`, `lot`.`wh_code`, `lot`.`item_code`, `lot`.`lot_att01`, `lot`.`lot_att02`, `lot`.`lot_att03`, `lot`.`lot_att04`, `lot`.`lot_att05`, `lot`.`lot_att06`, `lot`.`lot_att07`, `lot`.`lot_att08`, `lot`.`lot_att09`, `lot`.`lot_att10`, `lot`.`lot_att11`, `lot`.`lot_att12`, `lot`.`create_user_code`, `lot`.`create_user_name`, `lot`.`create_time`, `lot`.`update_user_code`, `lot`.`update_user_name`, `lot`.`update_time`, `lot`.`tenant_code`, `lot`.`remark`, `lot`.`delete_flag`, `lot`.`version`, `d1`.`name` AS `inventory_sts` FROM `wms_inv_anlianyun_656859700b3d`.`fu_inv_lot` AS `lot` LEFT JOIN `dict` AS `d1` ON `d1`.`code` = `lot`.`lot_att04` AND `d1`.`dict_code` = 'CL_INVENTORY_STS') AS `fu_inv_lot`) AS `src00_fu_inv_lot_752b`
2024-07-17 19:46:31,882 [http-nio-9080-exec-8] ERROR [supersonic_2fdcca85158b41a2b8f28de47b5b69ad] c.t.s.h.c.t.c.sql.node.SemanticNode 429 - optimize error {}
org.apache.calcite.runtime.CalciteContextException: From line 14, column 11 to line 14, column 52: Object 'dc_anlianyun_656859700b3d_ver' not found
        at sun.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:507)
        at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:948)
        at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:933)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5643)
        at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:183)
        at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:188)
        at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:95)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1164)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1135)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3539)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3518)

### What You Expected?

希望支持同一实例能连库，直接用生成的sql是可以查询的
![image](https://github.com/user-attachments/assets/ec04085c-d566-4c2e-9c21-a7c64bef231e)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jipeli** [comment]
"WITH dict AS (SELECT dict_code, code, name FROM dc_anlianyun_656859700b3d_ver.data_dictionary_detail) SELECT lot.id, lot.lot_num, lot.wh_code, lot.item_code, lot.lot_att01, lot.lot_att02, lot.lot_att03, lot.lot_att04, lot.lot_att05, lot.lot_att06, lot.lot_att07, lot.lot_att08, lot.lot_att09, lot.lot_att10, lot.lot_att11, lot.lot_att12, lot.create_user_code, lot.create_user_name, lot.create_time, lot.update_user_code, lot.update_user_name, lot.update_time, lot.tenant_code, lot.remark, lot.delete_flag, lot.version, d1.name AS inventory_sts FROM wms_inv_anlianyun_656859700b3d.fu_inv_lot AS lot LEFT JOIN dict AS d1 ON d1.code = lot.lot_att04 AND d1.dict_code = 'CL_INVENTORY_STS') AS fu_inv_lot"   模型的定义SQL不规范，可以试试 去掉后面的“) AS fu_inv_lot”  看看
