### ISSUE TITLE
windows环境下启动报错[java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=27009 must be within the inclusive range [-21128,21127]] 

### ISSUE THREAD

**Issue by ywf** [tencentmusic/supersonic#1444]
### Describe your question

环境：windows11
版本：0.9.4
在命令行执行.\supersonic-daemon.bat start，页面打不开，查看log日志error.chat.log，显示如下的错误：
2024-07-22 17:02:56,831 [main] ERROR [] c.t.s.c.s.impl.EmbeddingServiceImpl 50 - embeddingModel embed error question: 对比一下陈拙悬、孟梅琦、赖媚韵的粉丝数 (补充信息:’'1527896'‘是一个’MPPM歌手ID‘，’ '1565463'‘是一个’MPPM歌手ID‘，’ '2141459'‘是一个’MPPM歌手ID‘。当前的日期是2023-05-31) , embeddingStore: InMemoryEmbeddingStore
java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=27009 must be within the inclusive range [-21128,21127]
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:68)
	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:50)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)
	at com.tencent.supersonic.common.service.impl.EmbeddingServiceImpl.addQuery(EmbeddingServiceImpl.java:47)
	at com.tencent.supersonic.common.service.impl.ExemplarServiceImpl.storeExemplar(ExemplarServiceImpl.java:49)
	at com.tencent.supersonic.common.service.impl.ExemplarServiceImpl.lambda$loadSysExemplars$2(ExemplarServiceImpl.java:94)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.tencent.supersonic.common.service.impl.ExemplarServiceImpl.loadSysExemplars(ExemplarServiceImpl.java:94)
	at com.tencent.supersonic.common.service.impl.ExemplarServiceImpl.run(ExemplarServiceImpl.java:83)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=27009 must be within the inclusive range [-21128,21127]
	at ai.onnxruntime.OrtSession.run(Native Method)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:395)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:242)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:210)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.encode(OnnxBertBiEncoder.java:115)
	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:64)
	... 16 common frames omitted

**Comment by jerryjzhang** [comment]
这个看起来是OnnxRuntime动态库问题，是不是可以手动安装下，或者尝试用docker容器来部署

**Comment by BoyMarkSky** [comment]
可以在maven中去掉langchain4j-embeddings自定义嵌入模型的引用
