### ISSUE TITLE
winows环境idea启动报错

### ISSUE THREAD

**Issue by NoBug123** [tencentmusic/supersonic#1475]
### Describe your question

windows环境 idea启动报错Caused by: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.，访问http://localhost:9080/提示找不到 localhost 的网页，但是http://localhost:9080/swagger-ui/index.html页面能打开

### Provide any additional context or information

2024-07-29 18:01:58,862 [main] ERROR [] c.alibaba.druid.pool.DruidDataSource 1188 - testWhileIdle is true, validationQuery not set
2024-07-29 18:03:07,754 [main] ERROR [] c.alibaba.druid.filter.FilterManager 117 - load filter error, filter not found : 'stat'
2024-07-29 18:03:23,268 [main] ERROR [] c.t.s.h.chat.parser.llm.LLMSqlParser 71 - currentRetryRound:1, runText2SQL failed
java.lang.RuntimeException: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:194)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:140)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.lambda$generate$0(OnePassSCSqlGenStrategy.java:60)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.generate(OnePassSCSqlGenStrategy.java:57)
	at com.tencent.supersonic.headless.chat.parser.llm.JavaLLMProxy.text2sql(JavaLLMProxy.java:20)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMRequestService.runText2SQL(LLMRequestService.java:118)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:60)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:41)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.lambda$performParsing$1(WorkflowServiceImpl.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.performParsing(WorkflowServiceImpl.java:65)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.startWorkflow(WorkflowServiceImpl.java:41)
	at com.tencent.supersonic.headless.server.facade.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:156)
	at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:75)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.performParsing(ChatServiceImpl.java:74)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.parseAndExecute(ChatServiceImpl.java:114)
	at com.tencent.supersonic.demo.S2VisitsDemo.addSampleChats(S2VisitsDemo.java:144)
	at com.tencent.supersonic.demo.S2VisitsDemo.doRun(S2VisitsDemo.java:117)
	at com.tencent.supersonic.demo.S2BaseDemo.run(S2BaseDemo.java:98)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:194)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 40 common frames omitted
2024-07-29 18:55:13,886 [http-nio-9080-exec-1] ERROR [supersonic_a4dc1614db2f41c3b0667c9c0b8392d4] c.t.s.advice.RestExceptionHandler 32 - default global exception
com.tencent.supersonic.common.pojo.exception.AccessException: token is blank, get user failed
	at com.tencent.supersonic.auth.authentication.utils.UserTokenUtils.getUserWithPassword(UserTokenUtils.java:92)
	at com.tencent.supersonic.auth.authentication.interceptor.DefaultAuthenticationInterceptor.preHandle(DefaultAuthenticationInterceptor.java:61)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1058)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-07-29 18:59:04,658 [main] ERROR [] c.alibaba.druid.pool.DruidDataSource 1188 - testWhileIdle is true, validationQuery not set
2024-07-29 18:59:54,943 [main] ERROR [] c.alibaba.druid.filter.FilterManager 117 - load filter error, filter not found : 'stat'
2024-07-29 19:00:08,013 [main] ERROR [] c.t.s.h.chat.parser.llm.LLMSqlParser 71 - currentRetryRound:1, runText2SQL failed
java.lang.RuntimeException: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:194)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:140)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.lambda$generate$0(OnePassSCSqlGenStrategy.java:60)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.generate(OnePassSCSqlGenStrategy.java:57)
	at com.tencent.supersonic.headless.chat.parser.llm.JavaLLMProxy.text2sql(JavaLLMProxy.java:20)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMRequestService.runText2SQL(LLMRequestService.java:118)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:60)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:41)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.lambda$performParsing$1(WorkflowServiceImpl.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.performParsing(WorkflowServiceImpl.java:65)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.startWorkflow(WorkflowServiceImpl.java:41)
	at com.tencent.supersonic.headless.server.facade.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:156)
	at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:75)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.performParsing(ChatServiceImpl.java:74)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.parseAndExecute(ChatServiceImpl.java:114)
	at com.tencent.supersonic.demo.S2VisitsDemo.addSampleChats(S2VisitsDemo.java:144)
	at com.tencent.supersonic.demo.S2VisitsDemo.doRun(S2VisitsDemo.java:117)
	at com.tencent.supersonic.demo.S2BaseDemo.run(S2BaseDemo.java:98)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:194)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 40 common frames omitted
2024-07-29 19:00:10,103 [main] ERROR [] c.t.s.h.chat.parser.llm.LLMSqlParser 71 - currentRetryRound:2, runText2SQL failed
java.lang.RuntimeException: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:194)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:140)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.lambda$generate$0(OnePassSCSqlGenStrategy.java:60)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.generate(OnePassSCSqlGenStrategy.java:57)
	at com.tencent.supersonic.headless.chat.parser.llm.JavaLLMProxy.text2sql(JavaLLMProxy.java:20)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMRequestService.runText2SQL(LLMRequestService.java:118)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:60)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:41)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.lambda$performParsing$1(WorkflowServiceImpl.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.performParsing(WorkflowServiceImpl.java:65)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.startWorkflow(WorkflowServiceImpl.java:41)
	at com.tencent.supersonic.headless.server.facade.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:156)
	at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:75)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.performParsing(ChatServiceImpl.java:74)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.parseAndExecute(ChatServiceImpl.java:114)
	at com.tencent.supersonic.demo.S2VisitsDemo.addSampleChats(S2VisitsDemo.java:144)
	at com.tencent.supersonic.demo.S2VisitsDemo.doRun(S2VisitsDemo.java:117)
	at com.tencent.supersonic.demo.S2BaseDemo.run(S2BaseDemo.java:98)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:194)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 40 common frames omitted
2024-07-29 19:00:12,251 [main] ERROR [] c.t.s.h.chat.parser.llm.LLMSqlParser 71 - currentRetryRound:3, runText2SQL failed
java.lang.RuntimeException: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:194)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:140)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.lambda$generate$0(OnePassSCSqlGenStrategy.java:60)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.generate(OnePassSCSqlGenStrategy.java:57)
	at com.tencent.supersonic.headless.chat.parser.llm.JavaLLMProxy.text2sql(JavaLLMProxy.java:20)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMRequestService.runText2SQL(LLMRequestService.java:118)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:60)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:41)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.lambda$performParsing$1(WorkflowServiceImpl.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.performParsing(WorkflowServiceImpl.java:65)
	at com.tencent.supersonic.headless.server.web.service.impl.WorkflowServiceImpl.startWorkflow(WorkflowServiceImpl.java:41)
	at com.tencent.supersonic.headless.server.facade.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:156)
	at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:75)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.performParsing(ChatServiceImpl.java:74)
	at com.tencent.supersonic.chat.server.service.impl.ChatServiceImpl.parseAndExecute(ChatServiceImpl.java:114)
	at com.tencent.supersonic.demo.S2VisitsDemo.addSampleChats(S2VisitsDemo.java:144)
	at com.tencent.supersonic.demo.S2VisitsDemo.doRun(S2VisitsDemo.java:117)
	at com.tencent.supersonic.demo.S2BaseDemo.run(S2BaseDemo.java:98)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: dev.ai4j.openai4j.OpenAiHttpException: Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key.
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$1(OpenAiChatModel.java:194)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 40 common frames omitted

**Comment by jerryjzhang** [comment]
这个错只是会影响DEMO对话，不会导致页面无法访问（最新master版本已经做了优化，DEMO基本不会报错）。可以看下log日志里有没有其它报错。

**Comment by NoBug123** [comment]
感谢回复，源代码是昨天拉取的最新版本0.9.4,看了log没有其他报错。windows环境本地idea启动访问http://localhost:9080/
确实打不开，目前还没排查到原因。http://localhost:9080/swagger-ui/index.html是能打开的，具体如下图。
![企业微信截图_20240730101433](https://github.com/user-attachments/assets/82acac38-43c0-4c1c-9fbd-d4d42aab1d90)
![Uploading 企业微信截图_20240730101450.png…]()

**Comment by NoBug123** [comment]
你好，感谢回复。源码是昨天拉取的最新版本（0.9.4）。windows环境idea启动后看了下logs目录，只有chat对话的错误，如上（ Maximum number of tokens per request for demonstration purposes is 1000. If you wish to use more, please use your own OpenAI API key），目前还未排查到原因。另外访问http://localhost:9080/  无法打开，而http://localhost:9080/swagger-ui/index.html 是能正常访问的。如下图
![企业微信截图_20240730101824](https://github.com/user-attachments/assets/2920a726-ddd7-4bac-971d-0d959edf6392)
![企业微信截图_20240730101824](https://github.com/user-attachments/assets/40d3a3a5-e846-4b08-a5f3-cfa59b4f96cf)
