### ISSUE TITLE
[question] Startup error

### ISSUE THREAD

**Issue by jdzhang1221** [tencentmusic/supersonic#1572]
### Describe your question

The free quota of dashscope has been used up. The project startup initialization requires the embedded model quota. I can't start the project now, and I can't modify the embedded model. What should I do now?

The error is as follows：
Caused by: com.alibaba.dashscope.exception.ApiException: {"statusCode":400,"message":"Access denied, please make sure your account is in good standing.","code":"Arrearage","isJson":true,"requestId":"8af536f9-6b8b-93b5-bb5f-1597a3f65db4"}

### What have you tried to resolve your question

Comment the default prompt project

### Screenshots or Logs

2024-08-16 10:38:25,986 [main] ERROR [] c.t.s.c.s.impl.EmbeddingServiceImpl 62 - embeddingModel embed error question: 部门, embeddingStore: InMemoryEmbeddingStore
com.alibaba.dashscope.exception.ApiException: {"statusCode":400,"message":"Access denied, please make sure your account is in good standing.","code":"Arrearage","isJson":true,"requestId":"8af536f9-6b8b-93b5-bb5f-1597a3f65db4"}
	at com.alibaba.dashscope.protocol.okhttp.OkHttpHttpClient.send(OkHttpHttpClient.java:187)
	at com.alibaba.dashscope.api.SynchronizeHalfDuplexApi.call(SynchronizeHalfDuplexApi.java:58)
	at com.alibaba.dashscope.embeddings.TextEmbedding.call(TextEmbedding.java:90)
	at dev.langchain4j.model.dashscope.QwenEmbeddingModel.embedTexts(QwenEmbeddingModel.java:66)
	at dev.langchain4j.model.dashscope.QwenEmbeddingModel.embedAll(QwenEmbeddingModel.java:91)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)
	at com.tencent.supersonic.common.service.impl.EmbeddingServiceImpl.addQuery(EmbeddingServiceImpl.java:55)
	at com.tencent.supersonic.headless.server.task.MetaEmbeddingTask.reloadMetaEmbedding(MetaEmbeddingTask.java:74)
	at com.tencent.supersonic.headless.server.task.MetaEmbeddingTask.run(MetaEmbeddingTask.java:86)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: com.alibaba.dashscope.exception.ApiException: {"statusCode":400,"message":"Access denied, please make sure your account is in good standing.","code":"Arrearage","isJson":true,"requestId":"8af536f9-6b8b-93b5-bb5f-1597a3f65db4"}
	... 16 common frames omitted
2024-08-16 10:38:25,987 [main] INFO  [] c.t.s.h.s.task.MetaEmbeddingTask 80 - Embedding has been regularly reloaded  in 172037 milliseconds

**Comment by jdzhang1221** [comment]
java.lang.RuntimeException: java.io.InterruptedIOException: timeout
	at dev.langchain4j.model.ollama.OllamaClient.chat(OllamaClient.java:102)
	at dev.langchain4j.model.ollama.OllamaChatModel.lambda$generate$0(OllamaChatModel.java:87)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.ollama.OllamaChatModel.generate(OllamaChatModel.java:87)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.lambda$generate$0(OnePassSCSqlGenStrategy.java:64)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.tencent.supersonic.headless.chat.parser.llm.OnePassSCSqlGenStrategy.generate(OnePassSCSqlGenStrategy.java:61)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMRequestService.runText2SQL(LLMRequestService.java:120)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:59)
	at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:40)
	at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.lambda$performParsing$1(ChatWorkflowEngine.java:101)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.performParsing(ChatWorkflowEngine.java:100)
	at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.execute(ChatWorkflowEngine.java:57)
	at com.tencent.supersonic.headless.server.facade.service.impl.S2ChatLayerService.performParsing(S2ChatLayerService.java:93)
	at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:95)
	at com.tencent.supersonic.chat.server.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:115)
	at com.tencent.supersonic.chat.server.rest.ChatQueryController.parse(ChatQueryController.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.InterruptedIOException: timeout
	at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
	at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at dev.langchain4j.model.ollama.OllamaClient.chat(OllamaClient.java:94)
	... 81 common frames omitted

**Comment by jdzhang1221** [comment]
23:03:35 [main] ERROR c.t.s.c.s.impl.EmbeddingServiceImpl 62 - embeddingModel embed error question: 部门, embeddingStore: InMemoryEmbeddingStore
java.lang.RuntimeException: java.lang.RuntimeException: status code: 404; body: {"timestamp":"2024-08-16T15:03:39.622+00:00","status":404,"error":"Not Found","path":"/v4/embeddings/api/paas/v4/embeddings"}
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
	at dev.langchain4j.model.zhipu.ZhipuAiEmbeddingModel.lambda$embedAll$2(ZhipuAiEmbeddingModel.java:68)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4719)
	at java.util.Collections$2.forEachRemaining(Collections.java:4727)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at dev.langchain4j.model.zhipu.ZhipuAiEmbeddingModel.embedAll(ZhipuAiEmbeddingModel.java:69)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)
	at dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)
	at com.tencent.supersonic.common.service.impl.EmbeddingServiceImpl.addQuery(EmbeddingServiceImpl.java:55)
	at com.tencent.supersonic.headless.server.task.MetaEmbeddingTask.reloadMetaEmbedding(MetaEmbeddingTask.java:74)
	at com.tencent.supersonic.headless.server.task.MetaEmbeddingTask.run(MetaEmbeddingTask.java:86)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.tencent.supersonic.StandaloneLauncher.main(StandaloneLauncher.java:19)
Caused by: java.lang.RuntimeException: status code: 404; body: {"timestamp":"2024-08-16T15:03:39.622+00:00","status":404,"error":"Not Found","path":"/v4/embeddings/api/paas/v4/embeddings"}
	at dev.langchain4j.model.zhipu.ZhipuAiClient.toException(ZhipuAiClient.java:216)
	at dev.langchain4j.model.zhipu.ZhipuAiClient.embedAll(ZhipuAiClient.java:102)
	at dev.langchain4j.model.zhipu.ZhipuAiEmbeddingModel.lambda$embedAll$1(ZhipuAiEmbeddingModel.java:68)
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
	... 23 common frames omitted

**Comment by jdzhang1221** [comment]
already resolved
