### ISSUE TITLE
[question] doris数据库连接问题

### ISSUE THREAD

**Issue by Rsolut1on** [tencentmusic/supersonic#1654]
### Describe your question

连接成功Doris数据库后；
进行语义建模，快速创建可以提取表和字段名并进行配置。但SQL语句模式测试则同时显示“任务失败”和 “sussess”，提取不到数据和表。

经快速创建后，进行对话查询却查不出数据。所有问题均提示“意图解析失败”。

### Provide any additional context or information

#离线环境已测试大模型连通且在超音速库正常运行。 是数据库问题，未能读取到表中数据吗？

数据库，语义配置均已完成。

有一点，大模型聊天正常，超音速库问答正常。但是维度的别名自动生成功能也提示“大模型解析失败”。

### What have you tried to resolve your question

未能定位原因

### Your environment

linux、 离线环境

**Comment by Rsolut1on** [comment]
![Uploading 0240911215843.jpg…]()

**Comment by Rsolut1on** [comment]
![0240911215843](https://github.com/user-attachments/assets/12fe0b52-6903-405f-8f7f-52077c2666f0)
<img width="827" alt="微信图片_20240911215911" src="https://github.com/user-attachments/assets/b321bb0f-3825-4323-90cd-d2abdca36d36">
<img width="185" alt="微信图片_20240911215928" src="https://github.com/user-attachments/assets/9d2d11ab-2441-49b0-a082-6416971cf360">

**Comment by yinxing-wan** [comment]
同样遇到这个问题，我这边是超音速库都问答失败

**Comment by jerryjzhang** [comment]
可以提供一下info.chat.log和keypipeline.log日志文件吗？需要定位下是哪个环节的问题，潜在的异常场景包括：大模型解析异常、物理SQL生成异常、数据库执行异常等。

**Comment by yinxing-wan** [comment]
> 可以提供一下info.chat.log和keypipeline.log日志文件吗？需要定位下是哪个环节的问题，潜在的异常场景包括：大模型解析异常、物理SQL生成异常、数据库执行异常等。

2024-09-14 08:39:32,017 [http-nio-9080-exec-8] ERROR [supersonic_10c4ea781d274fc38b5b3206fbab4ea4] c.t.s.h.c.p.llm.LLMResponseService 67 - currentRetry:2,sql is not valid:SELECT [歌手名], SUM([播放量]) AS 总播放量 FROM [歌手库数据集] WHERE [播放量] > (SELECT MIN([播放量]) FROM [歌>手库数据集]) AND [播放量] < (SELECT MAX([播放量]) FROM [歌手库数据集]) AND [播放量] > (SELECT [播放量] FROM [歌手库数据集] WHERE [日期] = '2024-09-14') GROUP BY [歌手名] ORDER BY 总播放量 DESC LIMIT 1 
2024-09-14 08:39:32,017 [http-nio-9080-exec-8] INFO  [supersonic_10c4ea781d274fc38b5b3206fbab4ea4] c.t.s.h.chat.parser.llm.LLMSqlParser 57 - currentRetryRound:3, start runText2SQL 
2024-09-14 08:39:33,083 [http-nio-9080-exec-8] ERROR [supersonic_10c4ea781d274fc38b5b3206fbab4ea4] c.t.s.c.jsqlparser.SqlValidHelper 72 - isValidSQL parse:{} 
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT> 
    at line 1, column 1. 
 
Was expecting one of: 
 
    "WITH" 
 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:315) 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:116) 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:85) 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:62) 
        at com.tencent.supersonic.common.jsqlparser.SqlValidHelper.isValidSQL(SqlValidHelper.java:69) 
        at com.tencent.supersonic.headless.chat.parser.llm.LLMResponseService.getDeduplicationSqlResp(LLMResponseService.java:66) 
        at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:62) 
        at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:40) 
        at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.lambda$performParsing$1(ChatWorkflowEngine.java:101) 
        at java.util.ArrayList.forEach(ArrayList.java:1259) 
        at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.performParsing(ChatWorkflowEngine.java:100) 
        at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.execute(ChatWorkflowEngine.java:57) 
        at com.tencent.supersonic.headless.server.facade.service.impl.S2ChatLayerService.performParsing(S2ChatLayerService.java:93) 
        at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:95) 
        at com.tencent.supersonic.chat.server.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:115) 
        at com.tencent.supersonic.chat.server.rest.ChatQueryController.parse(ChatQueryController.java:47) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by yinxing-wan** [comment]
> 可以提供一下info.chat.log和keypipeline.log日志文件吗？需要定位下是哪个环节的问题，潜在的异常场景包括：大模型解析异常、物理SQL生成异常、数据库执行异常等。
`2024-09-14 08:39:32,017 [http-nio-9080-exec-8] ERROR [supersonic_10c4ea781d274fc38b5b3206fbab4ea4] c.t.s.h.c.p.llm.LLMResponseService 67 - currentRetry:2,sql is not valid:SELECT [歌手名], SUM([播放量]) AS 总播放量 FROM [歌手库数据集] WHERE [播放量] > (SELECT MIN([播放量]) FROM [歌>手库数据集]) AND [播放量] < (SELECT MAX([播放量]) FROM [歌手库数据集]) AND [播放量] > (SELECT [播放量] FROM [歌手库数据集] WHERE [日期] = '2024-09-14') GROUP BY [歌手名] ORDER BY 总播放量 DESC LIMIT 1 
2024-09-14 08:39:32,017 [http-nio-9080-exec-8] INFO  [supersonic_10c4ea781d274fc38b5b3206fbab4ea4] c.t.s.h.chat.parser.llm.LLMSqlParser 57 - currentRetryRound:3, start runText2SQL 
2024-09-14 08:39:33,083 [http-nio-9080-exec-8] ERROR [supersonic_10c4ea781d274fc38b5b3206fbab4ea4] c.t.s.c.jsqlparser.SqlValidHelper 72 - isValidSQL parse:{} 
net.sf.jsqlparser.JSQLParserException: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "SELECT" <K_SELECT> 
    at line 1, column 1. 
 
Was expecting one of: 
 
    "WITH" 
 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:315) 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:116) 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:85) 
        at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:62) 
        at com.tencent.supersonic.common.jsqlparser.SqlValidHelper.isValidSQL(SqlValidHelper.java:69) 
        at com.tencent.supersonic.headless.chat.parser.llm.LLMResponseService.getDeduplicationSqlResp(LLMResponseService.java:66) 
        at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.tryParse(LLMSqlParser.java:62) 
        at com.tencent.supersonic.headless.chat.parser.llm.LLMSqlParser.parse(LLMSqlParser.java:40) 
        at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.lambda$performParsing$1(ChatWorkflowEngine.java:101) 
        at java.util.ArrayList.forEach(ArrayList.java:1259) 
        at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.performParsing(ChatWorkflowEngine.java:100) 
        at com.tencent.supersonic.headless.server.utils.ChatWorkflowEngine.execute(ChatWorkflowEngine.java:57) 
        at com.tencent.supersonic.headless.server.facade.service.impl.S2ChatLayerService.performParsing(S2ChatLayerService.java:93) 
        at com.tencent.supersonic.chat.server.parser.NL2SQLParser.parse(NL2SQLParser.java:95) 
        at com.tencent.supersonic.chat.server.service.impl.ChatQueryServiceImpl.performParsing(ChatQueryServiceImpl.java:115) 
        at com.tencent.supersonic.chat.server.rest.ChatQueryController.parse(ChatQueryController.java:47) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

**Comment by yinxing-wan** [comment]
> 可以提供一下info.chat.log和keypipeline.log日志文件吗？需要定位下是哪个环节的问题，潜在的异常场景包括：大模型解析异常、物理SQL生成异常、数据库执行异常等。
这个是这里的log

![iwEdAqNwbmcDAQTRBQgF0QMRBrCSwMOEfOxaBQbNJS7JOT0AB9IsvVOICAAJomltCgAL0gACIFo png_720x720q90](https://github.com/user-attachments/assets/fa086cff-0bff-497a-94d1-33ab56ef742b)
![iwEdAqNwbmcDAQTRBYkF0QNBBrCE0lT6aSjd0QbNJT8fwr0AB9IsvVOICAAJomltCgAL0T9V png_720x720q90](https://github.com/user-attachments/assets/08da2678-ee35-4c84-8c69-c51a8cea26be)

**Comment by lxwcodemonkey** [comment]
我处理下 可能是SQL后面的 ; 导致

**Comment by lxwcodemonkey** [comment]
已提交 可以再试试SQL创建模型的方式 或者SQL后面先不加；符号

**Comment by yinxing-wan** [comment]
> 已提交 可以再试试SQL创建模型的方式 或者SQL后面先不加；符号

![iwEcAqNwbmcDAQTRCKoF0QEMBrAXMFNm9lCTjwbNcxLHercAB9IsvVOICAAJomltCgAL0gABaKM png_720x720q90](https://github.com/user-attachments/assets/771fc568-2460-443c-80ca-ecbf992bbde2)
![iwEcAqNwbmcDAQTRBSIF0QNzBrBAMI8OOwBNmAbNc0kvn10AB9IsvVOICAAJomltCgAL0gACA4A png_720x720q90](https://github.com/user-attachments/assets/1bd709be-3eeb-49cf-b852-ff0c2dcb9a20)
这个是字段映射配置问题吗？我好像是没调过的

**Comment by lxwcodemonkey** [comment]
这个看起来是大模型生成的SQL带有<>导致，这边用的是哪个大模型呢？

**Comment by yinxing-wan** [comment]
> 这个看起来是大模型生成的SQL带有<>导致，这边用的是哪个大模型呢？

现在用的是Qwen2 7B底座

**Comment by jerryjzhang** [comment]
复现率很高吗，我用qwen2:7b好像没有碰到过对字段加<>的输出

**Comment by yinxing-wan** [comment]
> 复现率很高吗，我用qwen2:7b好像没有碰到过对字段加<>的输出

我这边基本上都有加

**Comment by yinxing-wan** [comment]
> 复现率很高吗，我用qwen2:7b好像没有碰到过对字段加<>的输出
目前是超音数指标能够正常生成SQL，其他数据集还是存在问题？是否和数据库字符编码存在一定关系？
![iwEcAqNwbmcDAQTRBRIF0QI_BrAGAwZQSmPV8QbaTrpVEJkAB9IsvVOICAAJomltCgAL0gABt84 png_720x720q90](https://github.com/user-attach
![iwEcAqNwbmcDAQTRBQ4F0QI7BrDZXTSBJYgYawbaTvwYr4kAB9IsvVOICAAJomltCgAL0gABqe0 png_720x720q90](https://github.com/user-attachments/assets/6b903f0f-2d4e-486b-980c-267780c195cd)
ments/assets/9f410205-d34a-4b2f-8aff-0ece3eabd78d)

![iwEeAqNwbmcDAQTRCKAF0QKfBrD5P8eoKv2vkwbaTztG2SkAB9IsvVOICAAJomltCgAL0gADcQY png_720x720q90](https://github.com/user-attachments/assets/a8a257a1-515e-47df-a134-8d3df2db80c7)
![iwEcAqNwbmcDAQTRBQIF0QD6BrDijRYOsGOKjgbaT4460gsAB9IsvVOICAAJomltCgAL0XL5 png_720x720q90](https://github.com/user-attachments/assets/64bb891b-96e1-49a3-a66b-0fcdeb48932e)
