### ISSUE TITLE
[Bug] 启动时候使用向量库类型为默认的IN_MEMORY,启动日志中报错

### ISSUE THREAD

**Issue by zangma121** [tencentmusic/supersonic#1716]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.6

### What's Wrong?

18:07:57 [scheduling-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler 95 - Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: No enum constant com.tencent.supersonic.chat.api.pojo.enums.MemoryReviewResult.(POSITIVE)
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.tencent.supersonic.chat.api.pojo.enums.MemoryReviewResult.valueOf(MemoryReviewResult.java:4)
	at com.tencent.supersonic.chat.server.memory.MemoryReviewTask.lambda$review$0(MemoryReviewTask.java:70)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.tencent.supersonic.chat.server.memory.MemoryReviewTask.review(MemoryReviewTask.java:54)
	at jdk.internal.reflect.GeneratedMethodAccessor737.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)

### What You Expected?

没有错误

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
经过定位是由于大模型生成的结果不是约定的POSITIVE, NEGATIVE值，导致大模型评估任务失败；
预计优化点：一次评估失败不影响，整体的评估任务；
