### ISSUE TITLE
[Bug] 维度值设置中，导入字典显示成功，但是下面没有显示维度值，在问答对话中也不会被联想出来，而且有的能正常导入，有的时候不能

### ISSUE THREAD

**Issue by qintianliuxiaoxiao** [tencentmusic/supersonic#1892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

SuperSonic-0.9.8

### What's Wrong?

![image](https://github.com/user-attachments/assets/e21a2dc4-1ea1-4da0-b9fe-187626995cd6)
![image](https://github.com/user-attachments/assets/5329e5aa-e0ec-4782-aa27-6a6e6b119ec5)

后台的日志：
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.s.s.impl.DictTaskServiceImpl 84 - [addDictTask] dictTaskDO:DictTaskDO(id=null, name=dic_value_5_DIMENSION_26, description=null, type=DIMENSION, itemId=26, config=, status=pending, createdAt=Thu Nov 07 11:23:47 CST 2024, createdBy=admin, elapsedMs=null)
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.s.a.S2DataPermissionAspect 81 - needAuth is false, there is no need to check permissions.
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.s.f.s.i.S2SemanticLayerService 119 - [queryReq:QuerySqlReq(sql=SELECT package, count(1) FROM tbl WHERE (sys_imp_date >= '2024-11-06' AND sys_imp_date <= '2024-11-06') GROUP BY package ORDER BY count(1) DESC LIMIT 100000, limit=1000)]
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.core.cache.DefaultQueryCache 23 - query from cache, key:supersonic:dev:0:5:faf9001a98eff10ba507ed6d89481e0b,result:SemanticQueryResp(columns=[], sql=null, queryAuthorization=null, useCache=true, errorMsg=StatementCallback; bad SQL grammar [SELECT `package`, COUNT(*) FROM (SELECT `install_date` AS `sys_imp_date`, `package_name` AS `package`, `package_name` AS `user_events_1_internal_cnt` FROM `adsfall`.`event_aws_1`) AS `t4` WHERE `sys_imp_date` >= '2024-11-06' AND `sys_imp_date` <= '2024-11-06' GROUP BY `package` ORDER BY 2 DESC LIMIT 100000]; nested exception is java.sql.SQLException: Code: 246. DB::Exception: Bad size of marks file '/mnt/data4/cold/store/2ea/2ea8a094-13d3-47dc-b619-6a5d9fa83dc9/0ce2640130d971d3751a81e13308ad13_5440926_5456974_34/skp_idx_index_install_date.mrk2': 192, must be: 96. (CORRUPTED_DATA) (version 22.5.1.2079 (official build)) , server ClickHouseNode 
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.s.f.s.i.S2SemanticLayerService 129 - cacheKey:supersonic:dev:0:5:faf9001a98eff10ba507ed6d89481e0b,query:SemanticQueryResp(columns=[], sql=null, queryAuthorization=null, useCache=true, errorMsg=StatementCallback; bad SQL grammar [SELECT `package`, COUNT(*) FROM (SELECT `install_date` AS `sys_imp_date`, `package_name` AS `package`, `package_name` AS `user_events_1_internal_cnt` FROM `adsfall`.`event_aws_1`) AS `t4` WHERE `sys_imp_date` >= '2024-11-06' AND `sys_imp_date` <= '2024-11-06' GROUP BY `package` ORDER BY 2 DESC LIMIT 100000]; nested exception is java.sql.SQLException: Code: 246. DB::Exception: Bad size of marks file '/mnt/data4/cold/store/2ea/2ea8a094-13d3-47dc-b619-6a5d9fa83dc9/0ce2640130d971d3751a81e13308ad13_5440926_5456974_34/skp_idx_index_install_date.mrk2': 192, must be: 96. (CORRUPTED_DATA) (version 22.5.1.2079 (official build)) , server ClickHouseNode
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.c.k.file.FileHandlerImpl 219 - lines is empty
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.c.k.helper.FileHelper 29 - customPath:E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\,delete file:E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_1_DIMENSION_1.txt.bin
11:23:47 [http-nio-9080-exec-10] INFO  c.t.s.h.c.k.helper.HanlpHelper 108 - Custom dictionary has been reloaded in 41 milliseconds
11:23:47 [http-nio-9080-exec-1] WARN  c.t.s.h.c.k.file.FileHandlerImpl 191 - [getFileData] File does not exist: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt
11:23:47 [http-nio-9080-exec-1] WARN  c.t.s.h.c.k.file.FileHandlerImpl 161 - [getFileData] File does not exist: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt

后台有时候也会报这个错误，但是我没有删除过任何字典文件
11:23:29 [http-nio-9080-exec-4] WARN  c.t.s.h.c.k.file.FileHandlerImpl 191 - [getFileData] File does not exist: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt
11:23:29 [http-nio-9080-exec-4] WARN  c.t.s.h.c.k.file.FileHandlerImpl 161 - [getFileData] File does not exist: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt
11:23:35 [http-nio-9080-exec-8] INFO  c.t.s.h.c.k.file.FileHandlerImpl 208 - path:E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes.\data\dictionary\backup exists!
11:23:35 [http-nio-9080-exec-8] INFO  c.t.s.h.c.k.file.FileHandlerImpl 54 - Failed to copy file: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt
11:23:35 [http-nio-9080-exec-8] WARN  c.t.s.h.c.k.file.FileHandlerImpl 76 - Failed to delete file:E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt, e:
java.nio.file.NoSuchFileException: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1142)
	at com.tencent.supersonic.headless.chat.knowledge.file.FileHandlerImpl.deleteFile(FileHandlerImpl.java:73)
	at com.tencent.supersonic.headless.chat.knowledge.file.FileHandlerImpl.deleteDictFile(FileHandlerImpl.java:255)
	at com.tencent.supersonic.headless.server.service.impl.DictTaskServiceImpl.deleteDictTask(DictTaskServiceImpl.java:133)
	at com.tencent.supersonic.headless.server.rest.KnowledgeController.deleteDictTask(KnowledgeController.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
11:23:35 [http-nio-9080-exec-8] INFO  c.t.s.h.c.k.helper.FileHelper 29 - customPath:E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\,delete file:E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_1_DIMENSION_1.txt.bin
11:23:35 [http-nio-9080-exec-8] INFO  c.t.s.h.c.k.helper.HanlpHelper 108 - Custom dictionary has been reloaded in 71 milliseconds
11:23:35 [http-nio-9080-exec-8] INFO  c.t.s.h.s.s.impl.DictTaskServiceImpl 143 - [addDictTask] dictTaskDO:DictTaskDO(id=null, name=dic_value_5_DIMENSION_26, description=null, type=DIMENSION, itemId=26, config=, status=initial, createdAt=Thu Nov 07 11:23:35 CST 2024, createdBy=admin, elapsedMs=null)
11:23:35 [http-nio-9080-exec-9] WARN  c.t.s.h.c.k.file.FileHandlerImpl 191 - [getFileData] File does not exist: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt
11:23:35 [http-nio-9080-exec-9] WARN  c.t.s.h.c.k.file.FileHandlerImpl 161 - [getFileData] File does not exist: E:\SuperSonic\supersonic-master-0.9.8-V3\supersonic-master\launchers\standalone\target\classes\data\dictionary\custom\dic_value_5_DIMENSION_26.txt

### What You Expected?

能正常导入维度值

### How to Reproduce?

通过快速创建以及手动创建维度都无法正常导入维度值，设置为主键的是默认都不会创建维度吗？即使在建立模型的时候选择了快速创建好像也不会，主键创建维度都是需要手动的吗？我看超音数数据集里面的用户是主键，也有用户这个维度
![image](https://github.com/user-attachments/assets/a6aa7b10-473c-471b-a0f7-4c6d682b2645)

![image](https://github.com/user-attachments/assets/e2eaa9c2-35c2-41eb-b350-98f3c508a172)

### Anything Else?

无

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15074852943** [comment]
遇到相同的问题，请问解决了吗？要如何解决呢？

**Comment by 15074852943** [comment]
请问有解决的办法了吗？

**Comment by 15074852943** [comment]
好像发现问题了，已解决

**Comment by qintianliuxiaoxiao** [comment]
暂时还没有呢

**Comment by 15074852943** [comment]
> 暂时还没有呢

有些导入没成功的原因，可能是这个配置的问题，只查了一天的数据，可以通过修改这个配置解决，但是发现，还有其他原因会导入没有数据，看日志应该是缓存的问题，暂时这个问题未解决
![image](https://github.com/user-attachments/assets/5f9f8159-46c3-4ddc-a160-2291d311efe6)

**Comment by qintianliuxiaoxiao** [comment]
> > 暂时还没有呢
> 
> 有些导入没成功的原因，可能是这个配置的问题，只查了一天的数据，可以通过修改这个配置解决，但是发现，还有其他原因会导入没有数据，看日志应该是缓存的问题，暂时这个问题未解决 ![image](https://private-user-images.githubusercontent.com/84566665/398039013-5f9f8159-46c3-4ddc-a160-2291d311efe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjI2NDcsIm5iZiI6MTczNDkyMjM0NywicGF0aCI6Ii84NDU2NjY2NS8zOTgwMzkwMTMtNWY5ZjgxNTktNDZjMy00ZGRjLWExNjAtMjI5MWQzMTFlZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDAyNTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZmQ0NDI0OGI5YzE4OTA5ZGM1NzE3ZWFiNTY4NDA2ZGFiZTJkN2QzMzU5NzkxNTYyYjM4NjA5MWY0YzJjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1BRa2xho608jwbbri7TTKHU3IoEqcH36tnrMerdeKeQ)

好嘞，我去试试，谢谢啦
