### ISSUE TITLE
webpack failed in latest master branch

### ISSUE THREAD

**Issue by QuantumBear** [tencentmusic/supersonic#45]
`(node:53818) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:53818) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:53818) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (/Users/liusili/code/supersonic/webapp/packages/supersonic-fe/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:184161:18)
    at BulkUpdateDecorator.update (/Users/liusili/code/supersonic/webapp/packages/supersonic-fe/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:184062:50)
    at /Users/liusili/code/supersonic/webapp/packages/supersonic-fe/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:107101:9
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:449:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.1
lerna ERR! npm run build:os-local exited 1 in 'supersonic-fe'
lerna ERR! npm run build:os-local exited 1 in 'supersonic-fe'`

openssl version is LibreSSL 2.8.3.

**Comment by lexluo09** [comment]
Thank you for your issues. This could be a Node.js version issue.

**Comment by williamhuanliu** [comment]
This issue has been fixed, the code has been committed to the master branch, you can try it out, thank you. https://github.com/tencentmusic/supersonic/pull/61
